version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/backend.conf:/etc/nginx/backend.conf
      - ./nginx/cdn.conf:/etc/nginx/cdn.conf
      - ./nginx/logs:/var/log/nginx
      - cdn:/var/www/cdn
    command: /bin/bash -c "chmod -R 777 /var/www/cdn && nginx -g 'daemon off;'"
    networks:
      - app

  api1:
    build:
      context: .
      dockerfile: backend.dockerfile
    container_name: backend_container_1
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - app

  cron:
    build:
      context: .
      dockerfile: cronjobs.dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=acaidelivery
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword



networks:
  app:
    driver: bridge

volumes:
  db_data:
  cdn:
